"""cria tabelas de catalogo estoque vendas atendimento e avaliacoes

Revision ID: a6125052c5a1
Revises: e78926429dcd
Create Date: 2026-10-05 20:51:13.369711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6125052c5a1'
down_revision: Union[str, Sequence[str], None] = 'e78926429dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_produto',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria', name=op.f('pk_categoria_produto')),
    sa.UniqueConstraint('nome', name=op.f('uq_categoria_produto_nome'))
    )
    op.execute('ALTER TABLE "categoria_produto" ENABLE ROW LEVEL SECURITY')
    op.create_table('unidade',
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('despacha_online', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rua', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("tipo <> 'cd' OR despacha_online", name=op.f('ck_unidade_cd_despacha_online')),
    sa.CheckConstraint("tipo IN ('loja', 'cd')", name=op.f('ck_unidade_tipo_valido')),
    sa.PrimaryKeyConstraint('id_unidade', name=op.f('pk_unidade')),
    sa.UniqueConstraint('nome', name=op.f('uq_unidade_nome'))
    )
    op.execute('ALTER TABLE "unidade" ENABLE ROW LEVEL SECURITY')
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao_tecnica', sa.Text(), nullable=False),
    sa.Column('descricao_cliente', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_produto.id_categoria'], name=op.f('fk_produto_id_categoria_categoria_produto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_produto', name=op.f('pk_produto'))
    )
    op.execute('ALTER TABLE "produto" ENABLE ROW LEVEL SECURITY')
    op.create_table('endereco_cliente',
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=False),
    sa.Column('rua', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('fk_endereco_cliente_id_cliente_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_endereco', name=op.f('pk_endereco_cliente'))
    )
    op.execute('ALTER TABLE "endereco_cliente" ENABLE ROW LEVEL SECURITY')
    op.create_table('imagem_produto',
    sa.Column('id_imagem', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordem >= 1', name=op.f('ck_imagem_produto_ordem_positiva')),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], name=op.f('fk_imagem_produto_id_produto_produto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_imagem', name=op.f('pk_imagem_produto'))
    )
    op.execute('ALTER TABLE "imagem_produto" ENABLE ROW LEVEL SECURITY')
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('codigo_venda', sa.String(length=20), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_registrado_por', sa.Uuid(), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('motivo_cancelamento', sa.String(length=30), nullable=True),
    sa.Column('id_cancelado_por', sa.Uuid(), nullable=True),
    sa.Column('justificativa_cancelamento', sa.Text(), nullable=True),
    sa.Column('devolucao', sa.String(length=10), server_default='nenhuma', nullable=False),
    sa.Column('valor_frete', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pronto_retirada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reserva_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregue_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(canal = 'online') = (modalidade IS NOT NULL)", name=op.f('ck_pedido_modalidade_so_online')),
    sa.CheckConstraint("(status = 'cancelado') = (motivo_cancelamento IS NOT NULL)", name=op.f('ck_pedido_cancelado_exige_motivo')),
    sa.CheckConstraint("canal <> 'online' OR id_cliente IS NOT NULL", name=op.f('ck_pedido_online_exige_cliente')),
    sa.CheckConstraint("canal IN ('loja_fisica', 'online')", name=op.f('ck_pedido_canal_valido')),
    sa.CheckConstraint("devolucao IN ('nenhuma', 'parcial', 'total')", name=op.f('ck_pedido_devolucao_valida')),
    sa.CheckConstraint("modalidade IN ('entrega', 'retirada')", name=op.f('ck_pedido_modalidade_valida')),
    sa.CheckConstraint("motivo_cancelamento IN ('cliente', 'reserva_vencida', 'retirada_vencida', 'equipe')", name=op.f('ck_pedido_motivo_cancelamento_valido')),
    sa.CheckConstraint("motivo_cancelamento IS DISTINCT FROM 'equipe' OR (id_cancelado_por IS NOT NULL AND justificativa_cancelamento IS NOT NULL)", name=op.f('ck_pedido_cancelamento_equipe_exige_autor')),
    sa.CheckConstraint("status IN ('aguardando_pagamento', 'pago', 'enviado', 'pronto_retirada', 'entregue', 'cancelado')", name=op.f('ck_pedido_status_valido')),
    sa.CheckConstraint('valor_frete >= 0 AND valor_total >= 0', name=op.f('ck_pedido_valores_nao_negativos')),
    sa.ForeignKeyConstraint(['id_cancelado_por'], ['usuario.id_usuario'], name=op.f('fk_pedido_id_cancelado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('fk_pedido_id_cliente_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_registrado_por'], ['usuario.id_usuario'], name=op.f('fk_pedido_id_registrado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name=op.f('fk_pedido_id_unidade_unidade'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('pk_pedido')),
    sa.UniqueConstraint('codigo_venda', name=op.f('uq_pedido_codigo_venda'))
    )
    op.execute('ALTER TABLE "pedido" ENABLE ROW LEVEL SECURITY')
    op.create_table('transferencia',
    sa.Column('id_transferencia', sa.Integer(), nullable=False),
    sa.Column('id_unidade_origem', sa.Integer(), nullable=False),
    sa.Column('id_unidade_destino', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_solicitante', sa.Uuid(), nullable=False),
    sa.Column('id_enviado_por', sa.Uuid(), nullable=True),
    sa.Column('id_recebido_por', sa.Uuid(), nullable=True),
    sa.Column('id_cancelado_por', sa.Uuid(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('solicitada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'cancelada' OR motivo_cancelamento IS NOT NULL", name=op.f('ck_transferencia_cancelada_exige_motivo')),
    sa.CheckConstraint("status IN ('solicitada', 'enviada', 'recebida', 'cancelada')", name=op.f('ck_transferencia_status_valido')),
    sa.CheckConstraint('id_unidade_origem <> id_unidade_destino', name=op.f('ck_transferencia_origem_diferente_destino')),
    sa.ForeignKeyConstraint(['id_cancelado_por'], ['usuario.id_usuario'], name=op.f('fk_transferencia_id_cancelado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_enviado_por'], ['usuario.id_usuario'], name=op.f('fk_transferencia_id_enviado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_recebido_por'], ['usuario.id_usuario'], name=op.f('fk_transferencia_id_recebido_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_solicitante'], ['usuario.id_usuario'], name=op.f('fk_transferencia_id_solicitante_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade_destino'], ['unidade.id_unidade'], name=op.f('fk_transferencia_id_unidade_destino_unidade'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade_origem'], ['unidade.id_unidade'], name=op.f('fk_transferencia_id_unidade_origem_unidade'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_transferencia', name=op.f('pk_transferencia'))
    )
    op.execute('ALTER TABLE "transferencia" ENABLE ROW LEVEL SECURITY')
    op.create_table('variante',
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('tamanho', sa.String(length=20), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('preco >= 0', name=op.f('ck_variante_preco_nao_negativo')),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], name=op.f('fk_variante_id_produto_produto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_variante', name=op.f('pk_variante')),
    sa.UniqueConstraint('id_produto', 'cor', 'tamanho', name=op.f('uq_variante_id_produto_cor_tamanho')),
    sa.UniqueConstraint('sku', name=op.f('uq_variante_sku'))
    )
    op.execute('ALTER TABLE "variante" ENABLE ROW LEVEL SECURITY')
    op.create_table('endereco_entrega',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], name=op.f('fk_endereco_entrega_id_pedido_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('pk_endereco_entrega'))
    )
    op.execute('ALTER TABLE "endereco_entrega" ENABLE ROW LEVEL SECURITY')
    op.create_table('estoque',
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantidade_reservada', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('minimo_alterado_por', sa.Uuid(), nullable=True),
    sa.Column('minimo_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("canal IN ('loja_fisica', 'online')", name=op.f('ck_estoque_canal_valido')),
    sa.CheckConstraint('estoque_minimo IS NULL OR estoque_minimo >= 0', name=op.f('ck_estoque_minimo_nao_negativo')),
    sa.CheckConstraint('quantidade >= 0', name=op.f('ck_estoque_quantidade_nao_negativa')),
    sa.CheckConstraint('quantidade_reservada >= 0', name=op.f('ck_estoque_reservada_nao_negativa')),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name=op.f('fk_estoque_id_unidade_unidade'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_estoque_id_variante_variante'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['minimo_alterado_por'], ['usuario.id_usuario'], name=op.f('fk_estoque_minimo_alterado_por_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_variante', 'id_unidade', 'canal', name=op.f('pk_estoque'))
    )
    op.execute('ALTER TABLE "estoque" ENABLE ROW LEVEL SECURITY')
    op.create_table('historico_preco',
    sa.Column('id_historico_preco', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_novo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_alterado_por', sa.Uuid(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco_novo >= 0', name=op.f('ck_historico_preco_preco_nao_negativo')),
    sa.ForeignKeyConstraint(['id_alterado_por'], ['usuario.id_usuario'], name=op.f('fk_historico_preco_id_alterado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_historico_preco_id_variante_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_historico_preco', name=op.f('pk_historico_preco'))
    )
    op.execute('ALTER TABLE "historico_preco" ENABLE ROW LEVEL SECURITY')
    op.create_table('item_pedido',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('preco_unitario >= 0', name=op.f('ck_item_pedido_preco_nao_negativo')),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_item_pedido_quantidade_positiva')),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], name=op.f('fk_item_pedido_id_pedido_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_item_pedido_id_variante_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_item', name=op.f('pk_item_pedido'))
    )
    op.execute('ALTER TABLE "item_pedido" ENABLE ROW LEVEL SECURITY')
    op.create_table('item_transferencia',
    sa.Column('id_item_transferencia', sa.Integer(), nullable=False),
    sa.Column('id_transferencia', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('canal_saida', sa.String(length=20), nullable=False),
    sa.Column('canal_entrada', sa.String(length=20), nullable=False),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
    sa.Column('quantidade_enviada', sa.Integer(), nullable=True),
    sa.Column('quantidade_recebida', sa.Integer(), nullable=True),
    sa.CheckConstraint("canal_entrada IN ('loja_fisica', 'online')", name=op.f('ck_item_transferencia_canal_entrada_valido')),
    sa.CheckConstraint("canal_saida IN ('loja_fisica', 'online')", name=op.f('ck_item_transferencia_canal_saida_valido')),
    sa.CheckConstraint('quantidade_enviada IS NULL OR quantidade_enviada >= 0', name=op.f('ck_item_transferencia_enviada_nao_negativa')),
    sa.CheckConstraint('quantidade_recebida IS NULL OR quantidade_recebida >= 0', name=op.f('ck_item_transferencia_recebida_nao_negativa')),
    sa.CheckConstraint('quantidade_solicitada > 0', name=op.f('ck_item_transferencia_solicitada_positiva')),
    sa.ForeignKeyConstraint(['id_transferencia'], ['transferencia.id_transferencia'], name=op.f('fk_item_transferencia_id_transferencia_transferencia'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_item_transferencia_id_variante_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_item_transferencia', name=op.f('pk_item_transferencia'))
    )
    op.execute('ALTER TABLE "item_transferencia" ENABLE ROW LEVEL SECURITY')
    op.create_table('avaliacao',
    sa.Column('id_avaliacao', sa.Integer(), nullable=False),
    sa.Column('id_item_pedido', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='publicada', nullable=False),
    sa.Column('motivo_ocultacao', sa.Text(), nullable=True),
    sa.Column('id_ocultada_por', sa.Uuid(), nullable=True),
    sa.Column('ocultada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editada_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'oculta' OR (motivo_ocultacao IS NOT NULL AND id_ocultada_por IS NOT NULL)", name=op.f('ck_avaliacao_oculta_exige_motivo')),
    sa.CheckConstraint("status IN ('publicada', 'oculta')", name=op.f('ck_avaliacao_status_valido')),
    sa.CheckConstraint('nota BETWEEN 1 AND 5', name=op.f('ck_avaliacao_nota_de_1_a_5')),
    sa.ForeignKeyConstraint(['id_item_pedido'], ['item_pedido.id_item'], name=op.f('fk_avaliacao_id_item_pedido_item_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_ocultada_por'], ['usuario.id_usuario'], name=op.f('fk_avaliacao_id_ocultada_por_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_avaliacao', name=op.f('pk_avaliacao')),
    sa.UniqueConstraint('id_item_pedido', name=op.f('uq_avaliacao_id_item_pedido'))
    )
    op.execute('ALTER TABLE "avaliacao" ENABLE ROW LEVEL SECURITY')
    op.create_table('chamado',
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=False),
    sa.Column('id_responsavel', sa.Uuid(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_item_pedido', sa.Integer(), nullable=True),
    sa.Column('id_variante', sa.Integer(), nullable=True),
    sa.Column('id_chamado_anterior', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='aberto', nullable=False),
    sa.Column('prioridade', sa.String(length=10), nullable=True),
    sa.Column('motivo_encerramento', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assumido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'concluido') = (motivo_encerramento IS NOT NULL)", name=op.f('ck_chamado_concluido_exige_motivo')),
    sa.CheckConstraint("categoria IN ('duvida', 'problema_pedido', 'troca', 'devolucao', 'outro')", name=op.f('ck_chamado_categoria_valida')),
    sa.CheckConstraint("motivo_encerramento IN ('resolvido', 'desistencia', 'sem_resposta')", name=op.f('ck_chamado_motivo_encerramento_valido')),
    sa.CheckConstraint("prioridade IN ('baixa', 'media', 'alta')", name=op.f('ck_chamado_prioridade_valida')),
    sa.CheckConstraint("status IN ('aberto', 'em_andamento', 'concluido')", name=op.f('ck_chamado_status_valido')),
    sa.ForeignKeyConstraint(['id_chamado_anterior'], ['chamado.id_chamado'], name=op.f('fk_chamado_id_chamado_anterior_chamado'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('fk_chamado_id_cliente_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_item_pedido'], ['item_pedido.id_item'], name=op.f('fk_chamado_id_item_pedido_item_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], name=op.f('fk_chamado_id_pedido_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuario.id_usuario'], name=op.f('fk_chamado_id_responsavel_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name=op.f('fk_chamado_id_unidade_unidade'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_chamado_id_variante_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_chamado', name=op.f('pk_chamado'))
    )
    op.execute('ALTER TABLE "chamado" ENABLE ROW LEVEL SECURITY')
    op.create_table('denuncia_avaliacao',
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('id_avaliacao', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('id_analisada_por', sa.Uuid(), nullable=True),
    sa.Column('analisada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'pendente' OR (id_analisada_por IS NOT NULL AND analisada_em IS NOT NULL)", name=op.f('ck_denuncia_avaliacao_analisada_exige_autor')),
    sa.CheckConstraint("status IN ('pendente', 'procedente', 'improcedente')", name=op.f('ck_denuncia_avaliacao_status_valido')),
    sa.ForeignKeyConstraint(['id_analisada_por'], ['usuario.id_usuario'], name=op.f('fk_denuncia_avaliacao_id_analisada_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_avaliacao'], ['avaliacao.id_avaliacao'], name=op.f('fk_denuncia_avaliacao_id_avaliacao_avaliacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('fk_denuncia_avaliacao_id_cliente_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_denuncia', name=op.f('pk_denuncia_avaliacao')),
    sa.UniqueConstraint('id_avaliacao', 'id_cliente', name=op.f('uq_denuncia_avaliacao_id_avaliacao_id_cliente'))
    )
    op.execute('ALTER TABLE "denuncia_avaliacao" ENABLE ROW LEVEL SECURITY')
    op.create_table('foto_avaliacao',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_avaliacao', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordem BETWEEN 1 AND 5', name=op.f('ck_foto_avaliacao_ordem_de_1_a_5')),
    sa.ForeignKeyConstraint(['id_avaliacao'], ['avaliacao.id_avaliacao'], name=op.f('fk_foto_avaliacao_id_avaliacao_avaliacao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_foto', name=op.f('pk_foto_avaliacao')),
    sa.UniqueConstraint('id_avaliacao', 'ordem', name=op.f('uq_foto_avaliacao_id_avaliacao_ordem'))
    )
    op.execute('ALTER TABLE "foto_avaliacao" ENABLE ROW LEVEL SECURITY')
    op.create_table('historico_chamado',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Uuid(), nullable=False),
    sa.Column('campo_alterado', sa.String(length=30), nullable=False),
    sa.Column('valor_anterior', sa.String(length=255), nullable=True),
    sa.Column('valor_novo', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("campo_alterado IN ('status', 'responsavel', 'prioridade')", name=op.f('ck_historico_chamado_campo_valido')),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], name=op.f('fk_historico_chamado_id_autor_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamado.id_chamado'], name=op.f('fk_historico_chamado_id_chamado_chamado'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_historico', name=op.f('pk_historico_chamado'))
    )
    op.execute('ALTER TABLE "historico_chamado" ENABLE ROW LEVEL SECURITY')
    op.create_table('mensagem',
    sa.Column('id_mensagem', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Uuid(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('anexo_caminho', sa.String(length=500), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tamanho', sa.Integer(), nullable=True),
    sa.Column('interna', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('conteudo IS NOT NULL OR anexo_caminho IS NOT NULL', name=op.f('ck_mensagem_texto_ou_anexo')),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], name=op.f('fk_mensagem_id_autor_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamado.id_chamado'], name=op.f('fk_mensagem_id_chamado_chamado'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_mensagem', name=op.f('pk_mensagem'))
    )
    op.execute('ALTER TABLE "mensagem" ENABLE ROW LEVEL SECURITY')
    op.create_table('movimentacao_estoque',
    sa.Column('id_movimentacao', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_transferencia', sa.Integer(), nullable=True),
    sa.Column('id_chamado', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("canal IN ('loja_fisica', 'online')", name=op.f('ck_movimentacao_estoque_canal_valido')),
    sa.CheckConstraint("tipo IN ('saldo_inicial', 'recebimento', 'avaria', 'perda', 'ajuste', 'venda', 'retorno_cancelamento', 'devolucao', 'saida_troca', 'saida_transferencia', 'entrada_transferencia', 'saida_realocacao', 'entrada_realocacao')", name=op.f('ck_movimentacao_estoque_tipo_valido')),
    sa.CheckConstraint("tipo NOT IN ('avaria', 'perda', 'ajuste') OR motivo IS NOT NULL", name=op.f('ck_movimentacao_estoque_motivo_obrigatorio')),
    sa.CheckConstraint('num_nonnulls(id_pedido, id_transferencia, id_chamado) <= 1', name=op.f('ck_movimentacao_estoque_no_maximo_uma_origem')),
    sa.CheckConstraint('quantidade <> 0', name=op.f('ck_movimentacao_estoque_quantidade_nao_zero')),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamado.id_chamado'], name=op.f('fk_movimentacao_estoque_id_chamado_chamado'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], name=op.f('fk_movimentacao_estoque_id_pedido_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_transferencia'], ['transferencia.id_transferencia'], name=op.f('fk_movimentacao_estoque_id_transferencia_transferencia'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id_unidade'], name=op.f('fk_movimentacao_estoque_id_unidade_unidade'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_movimentacao_estoque_id_usuario_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['variante.id_variante'], name=op.f('fk_movimentacao_estoque_id_variante_variante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_movimentacao', name=op.f('pk_movimentacao_estoque'))
    )
    op.execute('ALTER TABLE "movimentacao_estoque" ENABLE ROW LEVEL SECURITY')
    op.create_table('pagamento',
    sa.Column('id_pagamento', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('id_pagamento_original', sa.Integer(), nullable=True),
    sa.Column('id_chamado', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('id_transacao_gateway', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(tipo = 'estorno') = (id_pagamento_original IS NOT NULL)", name=op.f('ck_pagamento_estorno_exige_original')),
    sa.CheckConstraint("metodo IN ('pix', 'credito', 'debito', 'dinheiro')", name=op.f('ck_pagamento_metodo_valido')),
    sa.CheckConstraint("status IN ('pendente', 'aprovado', 'recusado', 'expirado')", name=op.f('ck_pagamento_status_valido')),
    sa.CheckConstraint("tipo IN ('pagamento', 'estorno')", name=op.f('ck_pagamento_tipo_valido')),
    sa.CheckConstraint('valor > 0', name=op.f('ck_pagamento_valor_positivo')),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamado.id_chamado'], name=op.f('fk_pagamento_id_chamado_chamado'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pagamento_original'], ['pagamento.id_pagamento'], name=op.f('fk_pagamento_id_pagamento_original_pagamento'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], name=op.f('fk_pagamento_id_pedido_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_pagamento', name=op.f('pk_pagamento')),
    sa.UniqueConstraint('id_transacao_gateway', name=op.f('uq_pagamento_id_transacao_gateway'))
    )
    op.execute('ALTER TABLE "pagamento" ENABLE ROW LEVEL SECURITY')
    op.create_table('voto_util',
    sa.Column('id_avaliacao', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_avaliacao'], ['avaliacao.id_avaliacao'], name=op.f('fk_voto_util_id_avaliacao_avaliacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], name=op.f('fk_voto_util_id_cliente_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_avaliacao', 'id_cliente', name=op.f('pk_voto_util'))
    )
    op.execute('ALTER TABLE "voto_util" ENABLE ROW LEVEL SECURITY')
    op.create_foreign_key(op.f('fk_usuario_id_unidade_unidade'), 'usuario', 'unidade', ['id_unidade'], ['id_unidade'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_usuario_id_unidade_unidade'), 'usuario', type_='foreignkey')
    op.drop_table('voto_util')
    op.drop_table('pagamento')
    op.drop_table('movimentacao_estoque')
    op.drop_table('mensagem')
    op.drop_table('historico_chamado')
    op.drop_table('foto_avaliacao')
    op.drop_table('denuncia_avaliacao')
    op.drop_table('chamado')
    op.drop_table('avaliacao')
    op.drop_table('item_transferencia')
    op.drop_table('item_pedido')
    op.drop_table('historico_preco')
    op.drop_table('estoque')
    op.drop_table('endereco_entrega')
    op.drop_table('variante')
    op.drop_table('transferencia')
    op.drop_table('pedido')
    op.drop_table('imagem_produto')
    op.drop_table('endereco_cliente')
    op.drop_table('produto')
    op.drop_table('unidade')
    op.drop_table('categoria_produto')
    # ### end Alembic commands ###
