"""cria usuario e permissoes

Revision ID: d0a686154ec5
Revises: 
Create Date: 2026-10-05 17:06:58.241883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a686154ec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo_acesso',
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('eh_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_modelo', name=op.f('pk_modelo_acesso')),
    sa.UniqueConstraint('nome', name=op.f('uq_modelo_acesso_nome'))
    )
    op.execute('ALTER TABLE "modelo_acesso" ENABLE ROW LEVEL SECURITY')
    op.create_index('uq_modelo_acesso_admin_unico', 'modelo_acesso', ['eh_admin'], unique=True, postgresql_where=sa.text('eh_admin'))
    op.create_table('permissao',
    sa.Column('id_permissao', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_permissao', name=op.f('pk_permissao')),
    sa.UniqueConstraint('codigo', name=op.f('uq_permissao_codigo'))
    )
    op.execute('ALTER TABLE "permissao" ENABLE ROW LEVEL SECURITY')
    op.create_table('modelo_permissao',
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('id_permissao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo_acesso.id_modelo'], name=op.f('fk_modelo_permissao_id_modelo_modelo_acesso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_permissao'], ['permissao.id_permissao'], name=op.f('fk_modelo_permissao_id_permissao_permissao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_modelo', 'id_permissao', name=op.f('pk_modelo_permissao'))
    )
    op.execute('ALTER TABLE "modelo_permissao" ENABLE ROW LEVEL SECURITY')
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.Column('status_conta', sa.String(length=30), nullable=False),
    sa.Column('tentativas_ativacao', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id_modelo_acesso', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_conta IN ('pendente_ativacao', 'ativa', 'inativa')", name=op.f('ck_usuario_status_conta_valido')),
    sa.CheckConstraint("tipo_conta <> 'cliente' OR cpf IS NOT NULL", name=op.f('ck_usuario_cliente_exige_cpf')),
    sa.CheckConstraint("tipo_conta <> 'interna' OR id_modelo_acesso IS NOT NULL", name=op.f('ck_usuario_interna_exige_modelo')),
    sa.CheckConstraint("tipo_conta IN ('interna', 'cliente')", name=op.f('ck_usuario_tipo_conta_valido')),
    sa.ForeignKeyConstraint(['id_modelo_acesso'], ['modelo_acesso.id_modelo'], name=op.f('fk_usuario_id_modelo_acesso_modelo_acesso'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['auth.users.id'], name=op.f('fk_usuario_id_usuario_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuario')),
    sa.UniqueConstraint('cpf', name=op.f('uq_usuario_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.execute('ALTER TABLE "usuario" ENABLE ROW LEVEL SECURITY')
    op.create_table('usuario_permissao_excecao',
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_permissao', sa.Integer(), nullable=False),
    sa.Column('efeito', sa.String(length=20), nullable=False),
    sa.CheckConstraint("efeito IN ('acrescentar', 'retirar')", name=op.f('ck_usuario_permissao_excecao_efeito_valido')),
    sa.ForeignKeyConstraint(['id_permissao'], ['permissao.id_permissao'], name=op.f('fk_usuario_permissao_excecao_id_permissao_permissao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_usuario_permissao_excecao_id_usuario_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_permissao', name=op.f('pk_usuario_permissao_excecao'))
    )
    op.execute('ALTER TABLE "usuario_permissao_excecao" ENABLE ROW LEVEL SECURITY')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_permissao_excecao')
    op.drop_table('usuario')
    op.drop_table('modelo_permissao')
    op.drop_table('permissao')
    op.drop_index('uq_modelo_acesso_admin_unico', table_name='modelo_acesso', postgresql_where=sa.text('eh_admin'))
    op.drop_table('modelo_acesso')
    # ### end Alembic commands ###
